import { MigrationInterface, QueryRunner } from 'typeorm';

export class FirstMigration1763991473922 implements MigrationInterface {
  name = 'FirstMigration1763991473922';

  public async up(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(
      `CREATE TABLE "user_group_access" ("createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "deletedAt" TIMESTAMP WITH TIME ZONE, "id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL, "name" character varying(120) NOT NULL, CONSTRAINT "PK_60030deb6c9936e373d701c6c9e" PRIMARY KEY ("id"))`,
    );
    await queryRunner.query(
      `CREATE UNIQUE INDEX "IDX_59f77f63e11f39268c34f4af54" ON "user_group_access" ("name") `,
    );
    await queryRunner.query(
      `CREATE TABLE "user_groups" ("createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "deletedAt" TIMESTAMP WITH TIME ZONE, "id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL, "name" character varying(120) NOT NULL, "is_admin" boolean NOT NULL DEFAULT false, CONSTRAINT "PK_ea7760dc75ee1bf0b09ab9b3289" PRIMARY KEY ("id"))`,
    );
    await queryRunner.query(
      `CREATE UNIQUE INDEX "IDX_cfdb13ccb9e22f9108f4298301" ON "user_groups" ("name") `,
    );
    await queryRunner.query(
      `CREATE TYPE "public"."users_gender_enum" AS ENUM('male', 'female')`,
    );
    await queryRunner.query(
      `CREATE TABLE "users" ("createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "deletedAt" TIMESTAMP WITH TIME ZONE, "id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL, "userGroupId" integer, "username" character varying(150) NOT NULL, "password" character varying(255) NOT NULL, "firstname" character varying(100), "lastname" character varying(100), "nationalId" character varying(20), "birthdate" date, "gender" "public"."users_gender_enum", "mobileNumber" character varying(20), "loginCode" character varying(16), "email" character varying(191), "profile" jsonb, "address" text, "status" boolean NOT NULL DEFAULT false, CONSTRAINT "PK_a3ffb1c0c8416b9fc6f907b7433" PRIMARY KEY ("id"))`,
    );
    await queryRunner.query(
      `CREATE UNIQUE INDEX "IDX_fe0bb3f6520ee0469504521e71" ON "users" ("username") `,
    );
    await queryRunner.query(
      `CREATE UNIQUE INDEX "IDX_ce1bc61d1337a02b71d72f9d9a" ON "users" ("nationalId") WHERE "nationalId" IS NOT NULL`,
    );
    await queryRunner.query(
      `CREATE UNIQUE INDEX "IDX_61dc14c8c49c187f5d08047c98" ON "users" ("mobileNumber") `,
    );
    await queryRunner.query(
      `CREATE UNIQUE INDEX "IDX_e2dd77cb8a46c78d8ea34de039" ON "users" ("email") WHERE "email" IS NOT NULL`,
    );
    await queryRunner.query(
      `CREATE TABLE "token_blacklist" ("jti" uuid NOT NULL, "expires_at" TIMESTAMP WITH TIME ZONE NOT NULL, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "PK_73e5965ffdbd4a9f2de7c93043c" PRIMARY KEY ("jti"))`,
    );
    await queryRunner.query(
      `CREATE INDEX "idx_token_blacklist_expires" ON "token_blacklist" ("expires_at") `,
    );
    await queryRunner.query(
      `CREATE TABLE "otpTokens" ("createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "deletedAt" TIMESTAMP WITH TIME ZONE, "id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL, "userId" integer NOT NULL, "code" character varying(12) NOT NULL, "expiresAt" TIMESTAMP WITH TIME ZONE NOT NULL, "consumed" boolean NOT NULL DEFAULT false, "attempts" smallint NOT NULL DEFAULT '0', CONSTRAINT "PK_92596a658151051e043b924eba8" PRIMARY KEY ("id"))`,
    );
    await queryRunner.query(
      `CREATE INDEX "IDX_51c9cbbc162189cec940d664f4" ON "otpTokens" ("code") `,
    );
    await queryRunner.query(
      `CREATE TABLE "user_group_access_map" ("user_group_id" integer NOT NULL, "user_group_access_id" integer NOT NULL, CONSTRAINT "PK_0f6583dd070a247c7be97da5de0" PRIMARY KEY ("user_group_id", "user_group_access_id"))`,
    );
    await queryRunner.query(
      `CREATE INDEX "IDX_0505704e4faff7de0b3bff0069" ON "user_group_access_map" ("user_group_id") `,
    );
    await queryRunner.query(
      `CREATE INDEX "IDX_3ed998e42de07c282628a7b53f" ON "user_group_access_map" ("user_group_access_id") `,
    );
    await queryRunner.query(
      `ALTER TABLE "users" ADD CONSTRAINT "FK_8b96e0ec79394c7e66bf88a05aa" FOREIGN KEY ("userGroupId") REFERENCES "user_groups"("id") ON DELETE SET NULL ON UPDATE NO ACTION`,
    );
    await queryRunner.query(
      `ALTER TABLE "otpTokens" ADD CONSTRAINT "FK_176c67c0d6a48aa7090c971d483" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`,
    );
    await queryRunner.query(
      `ALTER TABLE "user_group_access_map" ADD CONSTRAINT "FK_0505704e4faff7de0b3bff00692" FOREIGN KEY ("user_group_id") REFERENCES "user_groups"("id") ON DELETE CASCADE ON UPDATE CASCADE`,
    );
    await queryRunner.query(
      `ALTER TABLE "user_group_access_map" ADD CONSTRAINT "FK_3ed998e42de07c282628a7b53fe" FOREIGN KEY ("user_group_access_id") REFERENCES "user_group_access"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`,
    );
  }

  public async down(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(
      `ALTER TABLE "user_group_access_map" DROP CONSTRAINT "FK_3ed998e42de07c282628a7b53fe"`,
    );
    await queryRunner.query(
      `ALTER TABLE "user_group_access_map" DROP CONSTRAINT "FK_0505704e4faff7de0b3bff00692"`,
    );
    await queryRunner.query(
      `ALTER TABLE "otpTokens" DROP CONSTRAINT "FK_176c67c0d6a48aa7090c971d483"`,
    );
    await queryRunner.query(
      `ALTER TABLE "users" DROP CONSTRAINT "FK_8b96e0ec79394c7e66bf88a05aa"`,
    );
    await queryRunner.query(
      `DROP INDEX "public"."IDX_3ed998e42de07c282628a7b53f"`,
    );
    await queryRunner.query(
      `DROP INDEX "public"."IDX_0505704e4faff7de0b3bff0069"`,
    );
    await queryRunner.query(`DROP TABLE "user_group_access_map"`);
    await queryRunner.query(
      `DROP INDEX "public"."IDX_51c9cbbc162189cec940d664f4"`,
    );
    await queryRunner.query(`DROP TABLE "otpTokens"`);
    await queryRunner.query(
      `DROP INDEX "public"."idx_token_blacklist_expires"`,
    );
    await queryRunner.query(`DROP TABLE "token_blacklist"`);
    await queryRunner.query(
      `DROP INDEX "public"."IDX_e2dd77cb8a46c78d8ea34de039"`,
    );
    await queryRunner.query(
      `DROP INDEX "public"."IDX_61dc14c8c49c187f5d08047c98"`,
    );
    await queryRunner.query(
      `DROP INDEX "public"."IDX_ce1bc61d1337a02b71d72f9d9a"`,
    );
    await queryRunner.query(
      `DROP INDEX "public"."IDX_fe0bb3f6520ee0469504521e71"`,
    );
    await queryRunner.query(`DROP TABLE "users"`);
    await queryRunner.query(`DROP TYPE "public"."users_gender_enum"`);
    await queryRunner.query(
      `DROP INDEX "public"."IDX_cfdb13ccb9e22f9108f4298301"`,
    );
    await queryRunner.query(`DROP TABLE "user_groups"`);
    await queryRunner.query(
      `DROP INDEX "public"."IDX_59f77f63e11f39268c34f4af54"`,
    );
    await queryRunner.query(`DROP TABLE "user_group_access"`);
  }
}
